[package]
name = "binary-heap-plus"
version = "0.1.5"
authors = ["SEKINE, Hideki <sekineh@me.com>"]
description = "Enhanced version of std::collections::BinaryHeap that supports max, min, and custom-order heaps."
license = "MIT"
repository = "https://github.com/sekineh/binary-heap-plus-rs"
readme = "README.md"
keywords = ["binary", "heap", "priority", "queue"]
category = ["data-structures", "algorithms", ]

[features]
serde1 = ["serde", "serde_derive"]

[dependencies]
serde = { version = "1", optional = true }
serde_derive = { version = "^1.0.38", optional = true }

[dev-dependencies]
serde_json = "1.0.39"

[badges]
travis-ci = { repository = "sekineh/binary-heap-plus-rs" }
appveyor = { repository = "sekineh/binary-heap-plus-rs" }